# See https://www.netlify.com/docs/netlify-toml-reference/

[build]
  publish = "_gh_pages"
  command = "npm run dist && npm run release-sri && npm run docs-production"

[context.v3-dev]
  command = "grunt prep-release && npm run sri"
